apiVersion: v1
kind: PersistentVolume
metadata:
    name: core-postgres-pv-volume
    labels:
        type: local
        app: core-postgres
spec:
    storageClassName: manual
    capacity:
        storage: 5Gi
    accessModes:
        - ReadWriteMany
    hostPath:
        path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: core-postgres-pv-claim
    labels:
        app: core-postgres
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 5Gi
